# Generated by Django 5.1.3 on 2024-12-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización'),
        ),
    ]
