# Generated by Django 5.1.3 on 2024-12-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_category_remove_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
